//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerRank.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Cases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackerRank.Tests.Cases", typeof(Cases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///53 129
        ///52 33 30
        ///37 53 20
        ///12 2 30
        ///16 6 67
        ///38 33 66
        ///33 50 71
        ///24 5 44
        ///36 42 55
        ///20 9 60
        ///34 26 36
        ///10 13 39
        ///42 44 74
        ///30 42 59
        ///17 18 50
        ///1 44 52
        ///32 19 70
        ///30 27 66
        ///24 37 73
        ///51 52 92
        ///12 37 89
        ///15 53 70
        ///40 37 56
        ///47 40 74
        ///16 11 52
        ///47 18 76
        ///27 3 82
        ///45 53 38
        ///12 15 80
        ///35 50 18
        ///22 33 70
        ///34 41 83
        ///53 52 22
        ///31 48 26
        ///53 44 71
        ///10 43 36
        ///42 6 65
        ///46 44 11
        ///31 33 77
        ///15 42 38
        ///7 40 93
        ///24 53 79
        ///38 6 66
        ///31 47 39
        ///44 25 71
        ///3 9 50
        ///40 31 76
        ///16 12 74
        ///18 42 13
        ///47 25 33
        ///5 35 55
        ///4 11 42
        ///44  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
    }
}
